


//ROOMS
export const GET_ROOMS = 'GET_ROOMS';
export const STORE_CURRENT_ROOM = 'STORE_CURRENT_ROOM';
export const LOG_ROOM_ERROR = 'LOG_ROOM_ERROR';


//ATTENDEE
export const CREATE_ATTENDEE = 'CREATE_ATTENDEE';
export const LOG_REGISTRATION_ERROR = 'LOG_REGISTRATION_ERROR';
export const GET_ATTENDEE_LIST = 'GET_ATTENDEE_LIST';
export const GET_ATTENDEE_DATA = 'GET_ATTENDEE_DATA';


//Authentication

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";



export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL';

export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

///QUESTION FORMS

export const GET_SESSIONS_BY_EVENT_ID = "GET_SESSIONS_BY_EVENT_ID"
export const LOG_FORM_ERROR = "LOG_FORM_ERROR";
export const STORE_FORMS = 'STORE_FORMS';
export const STORE_CURRENT_FORM = 'STORE_CURRENT_FORM';
 
